/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

/**
 *
 * @author user
 */
public class Accueil extends javax.swing.JFrame {
    
    String msg = " BIENVENUE DANS MON APPLICATION DE GESTION DE STAGIAIRES ";

   
    public Accueil() {
        initComponents();
        setLocationRelativeTo(this);
        new Thread(new Runnable() {
            @Override
            public void run() {
                while (true) {                    
                    char c = msg.charAt(0);
                    String rest = msg.substring(1);
                    msg = rest+c;
                    lmsg.setText(msg);
                    try {
                        Thread.sleep(150);
                    } catch (Exception e) {
                    }
                    
                }
                
                
                
            }
        }).start();
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lstagiaire = new javax.swing.JLabel();
        lenseignant = new javax.swing.JLabel();
        lformation = new javax.swing.JLabel();
        lnotes = new javax.swing.JLabel();
        labstagiaire = new javax.swing.JLabel();
        labens = new javax.swing.JLabel();
        labnote = new javax.swing.JLabel();
        labfor = new javax.swing.JLabel();
        lmsg = new javax.swing.JLabel();
        fondaccueil = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lstagiaire.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/Stagiaires.png"))); // NOI18N
        lstagiaire.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lstagiaireMouseClicked(evt);
            }
        });
        getContentPane().add(lstagiaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, -1, -1));

        lenseignant.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/Enseignant.png"))); // NOI18N
        lenseignant.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lenseignantMouseClicked(evt);
            }
        });
        getContentPane().add(lenseignant, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, -1, -1));

        lformation.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/Formations.png"))); // NOI18N
        getContentPane().add(lformation, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        lnotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/Notes.png"))); // NOI18N
        getContentPane().add(lnotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, -1, -1));

        labstagiaire.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labstagiaire.setForeground(new java.awt.Color(255, 255, 255));
        labstagiaire.setText("Stagiaire");
        getContentPane().add(labstagiaire, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, 70, 20));

        labens.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labens.setForeground(new java.awt.Color(255, 255, 255));
        labens.setText("Enseignant");
        getContentPane().add(labens, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, -1, -1));

        labnote.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labnote.setForeground(new java.awt.Color(255, 255, 255));
        labnote.setText("Notes");
        getContentPane().add(labnote, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 400, 50, 20));

        labfor.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        labfor.setForeground(new java.awt.Color(255, 255, 255));
        labfor.setText("Formation");
        getContentPane().add(labfor, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        lmsg.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lmsg.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(lmsg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 790, 30));

        fondaccueil.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/AccueilFond.png"))); // NOI18N
        getContentPane().add(fondaccueil, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 954, 615));

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lstagiaireMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lstagiaireMouseClicked
     
        Stagiaire st = new Stagiaire();
        st.setVisible(true);
    }//GEN-LAST:event_lstagiaireMouseClicked

    private void lenseignantMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lenseignantMouseClicked

FenetreEnseignant fe = new FenetreEnseignant();
fe.setVisible(true);
    }//GEN-LAST:event_lenseignantMouseClicked

    
    public static void main(String args[]) {
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Accueil.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Accueil().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel fondaccueil;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labens;
    private javax.swing.JLabel labfor;
    private javax.swing.JLabel labnote;
    private javax.swing.JLabel labstagiaire;
    private javax.swing.JLabel lenseignant;
    private javax.swing.JLabel lformation;
    private javax.swing.JLabel lmsg;
    private javax.swing.JLabel lnotes;
    private javax.swing.JLabel lstagiaire;
    // End of variables declaration//GEN-END:variables
}
