/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modele.*;

/**
 *
 * @author user
 */
public class Authentification extends javax.swing.JFrame {

    /**
     * Creates new form Authentification
     */
    public Authentification() {
        initComponents();
        setLocationRelativeTo(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        laut = new javax.swing.JLabel();
        paut = new javax.swing.JPanel();
        jtusername = new javax.swing.JTextField();
        lusername = new javax.swing.JLabel();
        lpassword = new javax.swing.JLabel();
        passf = new javax.swing.JPasswordField();
        blogin = new javax.swing.JButton();
        bannuler = new javax.swing.JButton();
        afond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        laut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/AuthentificationIcone.png"))); // NOI18N
        getContentPane().add(laut, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, 140));

        paut.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veuillez vous authentifier", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 14))); // NOI18N
        paut.setOpaque(false);

        jtusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtusernameActionPerformed(evt);
            }
        });

        lusername.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lusername.setText("Username:");

        lpassword.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lpassword.setText("Pssword:");

        javax.swing.GroupLayout pautLayout = new javax.swing.GroupLayout(paut);
        paut.setLayout(pautLayout);
        pautLayout.setHorizontalGroup(
            pautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pautLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lusername, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtusername, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                    .addComponent(passf))
                .addGap(55, 55, 55))
        );
        pautLayout.setVerticalGroup(
            pautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pautLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lusername))
                .addGap(18, 18, 18)
                .addGroup(pautLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lpassword, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(passf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        getContentPane().add(paut, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 250, 110));

        blogin.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        blogin.setText("Login");
        blogin.setOpaque(false);
        blogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bloginActionPerformed(evt);
            }
        });
        getContentPane().add(blogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 360, -1, -1));

        bannuler.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bannuler.setText("Annuler");
        bannuler.setOpaque(false);
        bannuler.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bannulerActionPerformed(evt);
            }
        });
        getContentPane().add(bannuler, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, -1, -1));

        afond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/AuthentificationFond.png"))); // NOI18N
        afond.setText("jLabel1");
        getContentPane().add(afond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bloginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bloginActionPerformed
        ConnectUtilisateur cu = new ConnectUtilisateur();
        boolean trouve = false;
        try {
            while (cu.rs.next()) {

                if (jtusername.getText().equals(cu.rs.getObject("username"))
                        && passf.getText().equals(cu.rs.getObject("password"))) {
                    trouve = true;
                    break;

                }

            }
            if (trouve == true) {
                Accueil ac = new Accueil();
                ac.setVisible(true);
                this.dispose();

            } else {
                            JOptionPane.showMessageDialog(this, "username ou password incorrecte");
                            jtusername.setText(null);
                            passf.setText(null);
                            passf.requestFocus();
                            

            }
            
        } catch (SQLException ex) {
            Logger.getLogger(Authentification.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bloginActionPerformed

    private void jtusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtusernameActionPerformed

    private void bannulerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bannulerActionPerformed


dispose();
    }//GEN-LAST:event_bannulerActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Authentification.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Authentification().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel afond;
    private javax.swing.JButton bannuler;
    private javax.swing.JButton blogin;
    private javax.swing.JTextField jtusername;
    private javax.swing.JLabel laut;
    private javax.swing.JLabel lpassword;
    private javax.swing.JLabel lusername;
    private javax.swing.JPasswordField passf;
    private javax.swing.JPanel paut;
    // End of variables declaration//GEN-END:variables
}
