/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vue;

import vue.*;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modele.*;

/**
 *
 * @author user
 */
public class Notes extends javax.swing.JFrame {

    Connecte co = new Connecte();
    PreparedStatement ps;
    DefaultTableModel dtm = new DefaultTableModel();
    ResultSet rs;

    /**
     * Creates new form Notes
     */
    public Notes() {
        initComponents();
        setLocationRelativeTo(this);
        lcivilite.setText(Stagiaire.jtnom.getText() + " " + Stagiaire.jtprenom.getText());
        lmatricule.setText(Stagiaire.tfmatricule.getText());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lcivilite = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lmatricule = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtnotes = new javax.swing.JTextField();
        jycoef = new javax.swing.JTextField();
        bafficher = new javax.swing.JButton();
        bajout = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lmoyenne = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lmention = new javax.swing.JLabel();
        ldecision = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableNotes = new javax.swing.JTable();
        lfondnotes = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(lcivilite, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 10, 90, 20));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel1.setText("Mr Mme");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 50, 20));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("Matricule:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 60, 20));
        getContentPane().add(lmatricule, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 100, 20));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel5.setText("Notes:");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 14, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel6.setText("Coefficient:");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, -1, -1));
        jPanel1.add(jtnotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 11, 163, -1));
        jPanel1.add(jycoef, new org.netbeans.lib.awtextra.AbsoluteConstraints(77, 37, 163, -1));

        bafficher.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bafficher.setText("Afficher");
        bafficher.setOpaque(false);
        bafficher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bafficherActionPerformed(evt);
            }
        });
        jPanel1.add(bafficher, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, -1, -1));

        bajout.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        bajout.setText("Ajouter");
        bajout.setOpaque(false);
        bajout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajoutActionPerformed(evt);
            }
        });
        jPanel1.add(bajout, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 70, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 270, 100));

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel7.setText("Moyenne:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, -1, -1));

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel8.setText("Mention:");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, -1, -1));
        getContentPane().add(lmoyenne, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 170, 20));

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel9.setText("Décision:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, -1, -1));
        getContentPane().add(lmention, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 110, 20));
        getContentPane().add(ldecision, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 250, 140, 20));

        tableNotes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tableNotes);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 270, 290, 80));

        lfondnotes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/AuthentificationFond.png"))); // NOI18N
        getContentPane().add(lfondnotes, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 390));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bajoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajoutActionPerformed
        String req = "insert into note(note, coeff, matricule)values(?, ?, ?)";
        try {
            ps = co.connectbd().prepareStatement(req);
            ps.setString(1, jtnotes.getText());
             ps.setString(2, jycoef.getText());
            ps.setString(3, lmatricule.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this, "insertion reussie");
            
            

            
        } catch (SQLException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
                        JOptionPane.showMessageDialog(this, "echec dinsertion");

        }


    }//GEN-LAST:event_bajoutActionPerformed

    private void bafficherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bafficherActionPerformed


        try {
            ps = co.connectbd().prepareStatement("select * from note");
            rs = ps.executeQuery();
            DefaultTableModel dtm = new DefaultTableModel();
            dtm.addColumn("Note");
            dtm.addColumn("Coeff");
            dtm.addColumn("Note * Coeff");
            while (rs.next()) {   
                
                dtm.addRow(new Object[]{rs.getObject("note"), rs.getObject("coeff"), (Float.parseFloat(rs.getObject("note").toString())* Integer.parseInt(rs.getObject("coeff").toString())) });
                tableNotes.setModel(dtm);
            }
            // TODO add your handling code here:
        } catch (SQLException ex) {
            Logger.getLogger(Notes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bafficherActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Notes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Notes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bafficher;
    private javax.swing.JButton bajout;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jtnotes;
    private javax.swing.JTextField jycoef;
    private javax.swing.JLabel lcivilite;
    private javax.swing.JLabel ldecision;
    private javax.swing.JLabel lfondnotes;
    private javax.swing.JLabel lmatricule;
    private javax.swing.JLabel lmention;
    private javax.swing.JLabel lmoyenne;
    private javax.swing.JTable tableNotes;
    // End of variables declaration//GEN-END:variables
}
